/*******************************************************
This program was created by the
CodeWizardAVR V3.12 Advanced
Automatic Program Generator
© Copyright 1998-2014 Pavel Haiduc, HP InfoTech s.r.l.
http://www.hpinfotech.com

Project : 
Version : 
Date    : 02-Apr-2021
Author  : 
Company : 
Comments: 


Chip type               : ATmega164A
Program type            : Application
AVR Core Clock frequency: 7.372800 MHz
Memory model            : Small
External RAM size       : 0
Data Stack size         : 256
*******************************************************/

#include <mega164a.h>
#include <delay.h> 
#include "defs.h"    
#include <stdlib.h>

//*************************************************************************************************
//*********** BEGIN SERIAL STUFF (interrupt-driven, generated by Code Wizard) *********************
//*************************************************************************************************

#ifndef RXB8
#define RXB8 1
#endif

#ifndef TXB8
#define TXB8 0
#endif

#ifndef UPE
#define UPE 2
#endif

#ifndef DOR
#define DOR 3
#endif

#ifndef FE
#define FE 4
#endif

#ifndef UDRE
#define UDRE 5
#endif

#ifndef RXC
#define RXC 7
#endif

#define FRAMING_ERROR (1<<FE)
#define PARITY_ERROR (1<<UPE)
#define DATA_OVERRUN (1<<DOR)
#define DATA_REGISTER_EMPTY (1<<UDRE)
#define RX_COMPLETE (1<<RXC)

// USART0 Receiver buffer
#define RX_BUFFER_SIZE0 8
char rx_buffer0[RX_BUFFER_SIZE0];

#if RX_BUFFER_SIZE0 <= 256
unsigned char rx_wr_index0,rx_rd_index0,rx_counter0;
#else
unsigned int rx_wr_index0,rx_rd_index0,rx_counter0;
#endif

// This flag is set on USART0 Receiver buffer overflow
bit rx_buffer_overflow0;

// USART0 Receiver interrupt service routine
interrupt [USART0_RXC] void usart0_rx_isr(void)
{
char status,data;
status=UCSR0A;
data=UDR0;
if ((status & (FRAMING_ERROR | PARITY_ERROR | DATA_OVERRUN))==0)
   {
   rx_buffer0[rx_wr_index0++]=data;
#if RX_BUFFER_SIZE0 == 256
   // special case for receiver buffer size=256
   if (++rx_counter0 == 0) rx_buffer_overflow0=1;
#else
   if (rx_wr_index0 == RX_BUFFER_SIZE0) rx_wr_index0=0;
   if (++rx_counter0 == RX_BUFFER_SIZE0)
      {
      rx_counter0=0;
      rx_buffer_overflow0=1;
      }
#endif
   }
}

#ifndef _DEBUG_TERMINAL_IO_
// Get a character from the USART0 Receiver buffer
#define _ALTERNATE_GETCHAR_
#pragma used+
char getchar(void)
{
char data;
while (rx_counter0==0);
data=rx_buffer0[rx_rd_index0++];
#if RX_BUFFER_SIZE0 != 256
if (rx_rd_index0 == RX_BUFFER_SIZE0) rx_rd_index0=0;
#endif
#asm("cli")
--rx_counter0;
#asm("sei")
return data;
}
#pragma used-
#endif

// USART0 Transmitter buffer
#define TX_BUFFER_SIZE0 8
char tx_buffer0[TX_BUFFER_SIZE0];

#if TX_BUFFER_SIZE0 <= 256
unsigned char tx_wr_index0,tx_rd_index0,tx_counter0;
#else
unsigned int tx_wr_index0,tx_rd_index0,tx_counter0;
#endif

// USART0 Transmitter interrupt service routine
interrupt [USART0_TXC] void usart0_tx_isr(void)
{
if (tx_counter0)
   {
   --tx_counter0;
   UDR0=tx_buffer0[tx_rd_index0++];
#if TX_BUFFER_SIZE0 != 256
   if (tx_rd_index0 == TX_BUFFER_SIZE0) tx_rd_index0=0;
#endif
   }
}

#ifndef _DEBUG_TERMINAL_IO_
// Write a character to the USART0 Transmitter buffer
#define _ALTERNATE_PUTCHAR_
#pragma used+
void putchar(char c)
{
while (tx_counter0 == TX_BUFFER_SIZE0);
#asm("cli")
if (tx_counter0 || ((UCSR0A & DATA_REGISTER_EMPTY)==0))
   {
   tx_buffer0[tx_wr_index0++]=c;
#if TX_BUFFER_SIZE0 != 256
   if (tx_wr_index0 == TX_BUFFER_SIZE0) tx_wr_index0=0;
#endif
   ++tx_counter0;
   }
else
   UDR0=c;
#asm("sei")
}
#pragma used-
#endif
//*************************************************************************************************
//********************END SERIAL STUFF (USART0)  **************************************************
//*************************************************************************************************
//*******   if you need USART1, enable it in Code Wizard and copy coresponding code here  *********
//*************************************************************************************************


// Declare your global variables here


char board[]={' ',' ',' ',' ',' ',' ',' ',' ',' ',' '};


// Timer 0 overflow interrupt service routine
interrupt [TIM0_OVF] void timer0_ovf_isr(void)
{
// Reinitialize Timer 0 value
TCNT0=0x1A;
// Place your code here

}
// ------------------------------------------------------//



void resetBoard()                 //oprim tensiunea de pe toti pinii A,C folositi
{
    PORTA = 0;
    PORTC = 0;
    PORTD.7 = 0;
    PORTD.4 = 0;
}

void resetBoard2(){                 // iteram prin fiecare element al matricei si il resetam la valoarea ' '
 int i;
 for(i=0;i<10;i++)
    board[i]=' ';
}

void printBoard(char board[]){             //activam pinul aferent pozitiei pe care o dorim in functie de mutarea pe care o facem (x sau 0)

      resetBoard();
      if(board[1]=='X') X1 = 1; 
      if(board[2]=='X') X2 = 1;
      if(board[3]=='X') X3 = 1;
      if(board[4]=='X') X4 = 1;
      if(board[5]=='X') X5 = 1;
      if(board[6]=='X') X6 = 1;
      if(board[7]=='X') X7 = 1;
      if(board[8]=='X') X8 = 1;
      if(board[9]=='X') X9 = 1;
      
      if(board[1]=='O') O1 = 1; 
      if(board[2]=='O') O2 = 1;
      if(board[3]=='O') O3 = 1;
      if(board[4]=='O') O4 = 1;
      if(board[5]=='O') O5 = 1;
      if(board[6]=='O') O6 = 1;
      if(board[7]=='O') O7 = 1;
      if(board[8]=='O') O8 = 1;
      if(board[9]=='O') O9 = 1;
      
}

void blink(int poz)             // clipitul ledului pentru a stii pozitia la care ne aflam si faptul ca inca nu a fost incheiata mutarea pentru X
{
    
        if(poz==1) 
        {
            X1=1;      
            delay_ms(500);
            X1=0;
            delay_ms(500);
        }           
         if(poz==2) 
        {
            X2=1;      
            delay_ms(500);
            X2=0;
            delay_ms(500);
        }
         if(poz==3) 
        {
            X3=1;      
            delay_ms(500);
            X3=0;
            delay_ms(500);
        }
         if(poz==4) 
        {
            X4=1;      
            delay_ms(500);
            X4=0;
            delay_ms(500);
        }
         if(poz==5) 
        {
            X5=1;      
            delay_ms(500);
            X5=0;
            delay_ms(500);
        }
         if(poz==6) 
        {
            X6=1;      
            delay_ms(500);
            X6=0;
            delay_ms(500);
        }
         if(poz==7) 
        {
            X7=1;      
            delay_ms(500);
            X7=0;
            delay_ms(500);
        }
         if(poz==8) 
        {
            X8=1;      
            delay_ms(500);
            X8=0;
            delay_ms(500);
        }
         if(poz==9) 
        {
            X9=1;      
            delay_ms(500);
            X9=0;
            delay_ms(500);
        }
}

void blinkO(int poz)                       // clipitul ledului pentru a stii pozitia la care ne aflam si faptul ca inca nu a fost incheiata mutarea pentru O
{
    
        if(poz==1) 
        {
            O1=1;      
            delay_ms(500);
            O1=0;
            delay_ms(500);
        }           
         if(poz==2) 
        {
            O2=1;      
            delay_ms(500);
            O2=0;
            delay_ms(500);
        }
         if(poz==3) 
        {
            O3=1;      
            delay_ms(500);
            O3=0;
            delay_ms(500);
        }
         if(poz==4) 
        {
            O4=1;      
            delay_ms(500);
            O4=0;
            delay_ms(500);
        }
         if(poz==5) 
        {
            O5=1;      
            delay_ms(500);
            O5=0;
            delay_ms(500);
        }
         if(poz==6) 
        {
            O6=1;      
            delay_ms(500);
            O6=0;
            delay_ms(500);
        }
         if(poz==7) 
        {
            O7=1;      
            delay_ms(500);
            O7=0;
            delay_ms(500);
        }
         if(poz==8) 
        {
            O8=1;      
            delay_ms(500);
            O8=0;
            delay_ms(500);
        }
         if(poz==9) 
        {
            O9=1;      
            delay_ms(500);
            O9=0;
            delay_ms(500);
        }
}



void insertLetter(char letter,int pos){         //se intoroduce in matrice la pozitia selectata valoarea X sau O
    board[pos]=letter;
}


#asm("sei")


void userInput(char c)                       // mutarea jucatorului
{
   int run = 1; 
   int poz = 1;
   while(run)
   {          
         while(board[poz]!=' ') poz++;               //sarim peste pozitiile ce au fost alese deja
        if(PINB.0 == 1) 
        {                                            
            poz++;       // incrementam pozitia prin apasarea butonului ok     
        }
        if(c == 'X')   blink(poz);    //sclipirea ledului pe care ne aflam in momentul respectiv
        if(c == 'O')   blinkO(poz);  
        if(poz == 10) poz=0;         // resetarea numaratorii in cazul in care ne rezgandim si vrem sa facem o mutare anterioara
        
        if(but_ok == 1 && board[poz] == ' ')
            {board[poz] = c; run = 0; return;} 
        printBoard(board);     
   }
}


int count(char board[]){           //numaram elementele libere de pe masa 
    int counter=0, i;
    for(i=0;i<10;i++){
        if(board[i]==' '){
            counter++;
        }
    }
    return counter;

}

int IsWinner(char b[],char l){                    //verificam daca jocul s-a incheiat dupa regulile clasice x si 0
    if(b[1]==l && b[2]==l && b[3]==l)
        return 1;
    else if (b[4]==l && b[5]==l && b[6]==l)
        return 1;
    else if (b[7]==l && b[8]==l && b[9]==l)
        return 1;
    else if (b[1]==l && b[4]==l && b[7]==l)
        return 1;
    else if (b[2]==l && b[5]==l && b[8]==l)
        return 1;
     else if (b[3]==l && b[6]==l && b[9]==l)
        return 1;
    else if (b[1]==l && b[5]==l && b[9]==l)
        return 1;
    else if (b[3]==l && b[5]==l && b[7]==l)
        return 1;
    else
        return 0;    
}

int isBoardFull(char board[]){    // verificam daca sunt mai mult de doua locuri ramase libere
    if(count(board)>2)       // comparam cu 2 deoarece vectorul nostru are 10 elemente, pozitia 0 am pastrat-o pentru incheierea jocului
        return 0;
    else
        return 1;
}

int computerMove(){             //alegerea aleatorie a mutarii calculatorului
    int move=0;
    int pozitii_libere[10];
    int k=0;
    int i; 
    int array_size;
    for(i=1;i<10;i++){
        if(board[i]==' '){
            pozitii_libere[k]=i;   //introducem intr-un nou vector pozitiile libere la momentul respctiv
            k++;
        }
    }
   
  array_size  = ( sizeof((pozitii_libere)) / sizeof((pozitii_libere[0])))-(10-k);    //calculam dimensiunea vectorului (nr de elemente)
   
        move=pozitii_libere[rand() % array_size];    // alegem o pozitie aleatorie din cele libere cu ajutorul functiei rand();
        return move;
    return 0;
   
}



// --- AFISARE WIN / LOSE / TIE ---
void Xwin()                    //afisarea unui X in cazul in care castiga playerul 
{
    int i;
    for(i=1; i<=3; i++)
    {
        X1 = 1;
        X3 = 1;
        X5 = 1;
        X7 = 1;
        X9 = 1;
        delay_ms(750);   
        X1 = 0;
        X3 = 0;
        X5 = 0;
        X7 = 0;
        X9 = 0;
        delay_ms(750);
        
    }  
    resetBoard2();
    resetBoard();
}

void Owin()        //afisarea unui O in cazul in care castiga computerul
{
    int i;
    for(i=1; i<=3; i++)
    {
        O1 = 1;
        O2 = 1;
        O3 = 1;  
        O4 = 1;
        O6 = 1;
        O7 = 1;
        O8 = 1;
        O9 = 1;
        delay_ms(750);    
        O1 = 0;
        O2 = 0;
        O3 = 0;  
        O4 = 0;
        O6 = 0;
        O7 = 0;
        O8 = 0;
        O9 = 0;
        delay_ms(750);
        
    }   
     resetBoard(); 
     resetBoard2(); 
}


void tie()               //afisarea unui T in cazul remizei
{
    int i;
    for(i=1; i<=3; i++)
    {
        X1 = 1; 
        X2 = 1;
        X3 = 1;
        X5 = 1;
        X8 = 1;
        delay_ms(750);
        X1 = 0; 
        X2 = 0;
        X3 = 0;
        X5 = 0;
        X8 = 0;
        delay_ms(750);        
    }  
     resetBoard(); 
     resetBoard2(); 
}

// --- JOC NOU ---

void joc(){           //introducerea functiilor anterioare pentru a crea jocul
    int move; 
    
    while(!isBoardFull(board)){    //verificam daca mai sunt pozitii libere
        if(!IsWinner(board,'O')){     // verificam daca a castigat Computerul
            userInput('X');           // playerul executa miscarea
            resetBoard();             
            printBoard(board);         //afisearea matricei dupa mutarea jucatorului
        }
        else{
            break;
        } 
    
    
    if(!IsWinner(board,'X')){    // verificam daca a castigat playerul
        move=computerMove();       
        if(move==0)              //daca singura pozitie ramasa e 0 jocul se incheie
            {delay_ms(1000); resetBoard();  tie();}        //tie
        else{
            insertLetter('O',move);    //daca nu, computerul misca       
            printBoard(board);        //afisearea matricei dupa mutarea computerului
        }
    }    
    
    
    else{ 
        delay_ms(1000);
        resetBoard(); 
        Xwin();                         //win 
        return;
    }
    if(isBoardFull(board))
        {delay_ms(1000); resetBoard(); Owin(); return; }                        //lose
    }
   
}








// ------------------------------ 
void main(void)
{
// Declare your local variables here

// Crystal Oscillator division factor: 1
#pragma optsize-
CLKPR=(1<<CLKPCE);
CLKPR=(0<<CLKPCE) | (0<<CLKPS3) | (0<<CLKPS2) | (0<<CLKPS1) | (0<<CLKPS0);
#ifdef _OPTIMIZE_SIZE_
#pragma optsize+
#endif

// Input/Output Ports initialization
// Port A initialization
// Function: Bit7=In Bit6=In Bit5=In Bit4=In Bit3=In Bit2=In Bit1=In Bit0=In 
DDRA=(0<<DDA7) | (0<<DDA6) | (0<<DDA5) | (0<<DDA4) | (0<<DDA3) | (0<<DDA2) | (0<<DDA1) | (0<<DDA0);
// State: Bit7=T Bit6=T Bit5=T Bit4=T Bit3=T Bit2=T Bit1=T Bit0=T 
PORTA=(0<<PORTA7) | (0<<PORTA6) | (0<<PORTA5) | (0<<PORTA4) | (0<<PORTA3) | (0<<PORTA2) | (0<<PORTA1) | (0<<PORTA0);

// Port B initialization
// Function: Bit7=In Bit6=In Bit5=In Bit4=In Bit3=In Bit2=In Bit1=In Bit0=In 
DDRB=(0<<DDB7) | (0<<DDB6) | (0<<DDB5) | (0<<DDB4) | (0<<DDB3) | (0<<DDB2) | (0<<DDB1) | (0<<DDB0);
// State: Bit7=T Bit6=T Bit5=T Bit4=T Bit3=T Bit2=T Bit1=T Bit0=T 
PORTB=(0<<PORTB7) | (0<<PORTB6) | (0<<PORTB5) | (0<<PORTB4) | (0<<PORTB3) | (0<<PORTB2) | (0<<PORTB1) | (0<<PORTB0);

// Port C initialization
// Function: Bit7=In Bit6=In Bit5=In Bit4=In Bit3=In Bit2=In Bit1=In Bit0=In 
DDRC=(0<<DDC7) | (0<<DDC6) | (0<<DDC5) | (0<<DDC4) | (0<<DDC3) | (0<<DDC2) | (0<<DDC1) | (0<<DDC0);
// State: Bit7=T Bit6=T Bit5=T Bit4=T Bit3=T Bit2=T Bit1=T Bit0=T 
PORTC=(0<<PORTC7) | (0<<PORTC6) | (0<<PORTC5) | (0<<PORTC4) | (0<<PORTC3) | (0<<PORTC2) | (0<<PORTC1) | (0<<PORTC0);

// Port D initialization
// Function: Bit7=In Bit6=In Bit5=In Bit4=In Bit3=In Bit2=In Bit1=In Bit0=In 
DDRD=(0<<DDD7) | (1<<DDD6) | (1<<DDD5) | (0<<DDD4) | (1<<DDD3) | (1<<DDD2) | (1<<DDD1) | (1<<DDD0);
// State: Bit7=T Bit6=T Bit5=T Bit4=T Bit3=T Bit2=T Bit1=T Bit0=T 
PORTD=(0<<PORTD7) | (0<<PORTD6) | (0<<PORTD5) | (0<<PORTD4) | (0<<PORTD3) | (0<<PORTD2) | (0<<PORTD1) | (0<<PORTD0);

// Timer/Counter 0 initialization
// Clock source: System Clock
// Clock value: 115.200 kHz
// Mode: Normal top=0xFF
// OC0A output: Disconnected
// OC0B output: Disconnected
// Timer Period: 1.9965 ms
TCCR0A=(0<<COM0A1) | (0<<COM0A0) | (0<<COM0B1) | (0<<COM0B0) | (0<<WGM01) | (0<<WGM00);
TCCR0B=(0<<WGM02) | (0<<CS02) | (1<<CS01) | (1<<CS00);
TCNT0=0x1A;
OCR0A=0x00;
OCR0B=0x00;

// Timer/Counter 1 initialization
// Clock source: System Clock
// Clock value: Timer1 Stopped
// Mode: Normal top=0xFFFF
// OC1A output: Disconnected
// OC1B output: Disconnected
// Noise Canceler: Off
// Input Capture on Falling Edge
// Timer1 Overflow Interrupt: Off
// Input Capture Interrupt: Off
// Compare A Match Interrupt: Off
// Compare B Match Interrupt: Off
TCCR1A=(0<<COM1A1) | (0<<COM1A0) | (0<<COM1B1) | (0<<COM1B0) | (0<<WGM11) | (0<<WGM10);
TCCR1B=(0<<ICNC1) | (0<<ICES1) | (0<<WGM13) | (0<<WGM12) | (0<<CS12) | (0<<CS11) | (0<<CS10);
TCNT1H=0x00;
TCNT1L=0x00;
ICR1H=0x00;
ICR1L=0x00;
OCR1AH=0x00;
OCR1AL=0x00;
OCR1BH=0x00;
OCR1BL=0x00;

// Timer/Counter 2 initialization
// Clock source: System Clock
// Clock value: Timer2 Stopped
// Mode: Normal top=0xFF
// OC2A output: Disconnected
// OC2B output: Disconnected
ASSR=(0<<EXCLK) | (0<<AS2);
TCCR2A=(0<<COM2A1) | (0<<COM2A0) | (0<<COM2B1) | (0<<COM2B0) | (0<<WGM21) | (0<<WGM20);
TCCR2B=(0<<WGM22) | (0<<CS22) | (0<<CS21) | (0<<CS20);
TCNT2=0x00;
OCR2A=0x00;
OCR2B=0x00;

// Timer/Counter 0 Interrupt(s) initialization
TIMSK0=(0<<OCIE0B) | (0<<OCIE0A) | (1<<TOIE0);

// Timer/Counter 1 Interrupt(s) initialization
TIMSK1=(0<<ICIE1) | (0<<OCIE1B) | (0<<OCIE1A) | (0<<TOIE1);

// Timer/Counter 2 Interrupt(s) initialization
TIMSK2=(0<<OCIE2B) | (0<<OCIE2A) | (0<<TOIE2);

// External Interrupt(s) initialization
// INT0: Off
// INT1: Off
// INT2: Off
// Interrupt on any change on pins PCINT0-7: Off
// Interrupt on any change on pins PCINT8-15: Off
// Interrupt on any change on pins PCINT16-23: Off
// Interrupt on any change on pins PCINT24-31: Off
EICRA=(0<<ISC21) | (0<<ISC20) | (0<<ISC11) | (0<<ISC10) | (0<<ISC01) | (0<<ISC00);
EIMSK=(0<<INT2) | (0<<INT1) | (0<<INT0);
PCICR=(0<<PCIE3) | (0<<PCIE2) | (0<<PCIE1) | (0<<PCIE0);

// USART0 initialization
// USART0 disabled
UCSR0B=(0<<RXCIE0) | (0<<TXCIE0) | (0<<UDRIE0) | (0<<RXEN0) | (0<<TXEN0) | (0<<UCSZ02) | (0<<RXB80) | (0<<TXB80);

// USART1 initialization
// USART1 disabled
UCSR1B=(0<<RXCIE1) | (0<<TXCIE1) | (0<<UDRIE1) | (0<<RXEN1) | (0<<TXEN1) | (0<<UCSZ12) | (0<<RXB81) | (0<<TXB81);

// Analog Comparator initialization
// Analog Comparator: Off
// The Analog Comparator's positive input is
// connected to the AIN0 pin
// The Analog Comparator's negative input is
// connected to the AIN1 pin
ACSR=(1<<ACD) | (0<<ACBG) | (0<<ACO) | (0<<ACI) | (0<<ACIE) | (0<<ACIC) | (0<<ACIS1) | (0<<ACIS0);
ADCSRB=(0<<ACME);
// Digital input buffer on AIN0: On
// Digital input buffer on AIN1: On
DIDR1=(0<<AIN0D) | (0<<AIN1D);

// ADC initialization
// ADC disabled
ADCSRA=(0<<ADEN) | (0<<ADSC) | (0<<ADATE) | (0<<ADIF) | (0<<ADIE) | (0<<ADPS2) | (0<<ADPS1) | (0<<ADPS0);

// SPI initialization
// SPI disabled
SPCR=(0<<SPIE) | (0<<SPE) | (0<<DORD) | (0<<MSTR) | (0<<CPOL) | (0<<CPHA) | (0<<SPR1) | (0<<SPR0);

// TWI initialization
// TWI disabled
TWCR=(0<<TWEA) | (0<<TWSTA) | (0<<TWSTO) | (0<<TWEN) | (0<<TWIE);

// Global enable interrupts
#asm("sei")


DDRA = 0xFF;
DDRC = 0xFF;
DDRD = (1<<DDD7) | (1<<DDD4);
while (1)
      {         
            joc();}
            delay_ms(5000);
           
           resetBoard(); 
           resetBoard2(); 
           
             
      
}